permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: kramdown

kramdown:
  input: GFM

# 作者信息
author: 
  name: 陈宇翔
  email: csyuxiang1988@gmail.com
  link: http://playdba.com
  weibo: http://weibo.com/mchenyuxiang
  github: http://github.com/mchenyuxiang

# 站点信息
title: 陈宇翔的博客 
description: 陈宇翔的博客
url: http://playdba.com
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/upload/touxiang.jpg
favicon: /public/upload/touxiang.jpg

# google analytics 设置
ga:
  id: UA-58840215-1
  url: playdba.com

# disqus 设置
disqus:
  shortname: mchenyuxiang

# 主题设置，自动激活某个标签
active: 技术

# 首页除了最新文章外显示分类
cates: 
  - Database
  - Android
  - IOS

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
  content: 目录
